# https://taskfile.dev

version: '3'

vars:
  CURRENT_DIR:
    sh: pwd
  SUFFIX: '{{if eq OS "windows"}}.exe{{end}}'

tasks:
  default:
    cmds:
      - task --list-all

  lint:
    cmds:
      - docker run --rm -v {{toSlash .CURRENT_DIR}}:/app -w /app golangci/golangci-lint:v2.5.0 golangci-lint run -v --timeout 5m

  upgrade-libraries:
    cmds:
      - go get go@latest
      - go get -u ./...
      - go fmt ./cmd/s3copy
      - go mod tidy
      - go mod verify

  tidy:
    cmds:
      - go fmt ./cmd/s3copy
      - go mod tidy -v

  audit:
    cmds:
      - go vet ./cmd/s3copy
      - go mod verify

  test:
    cmds:
      - go test -v ./cmd/s3copy

  bench:
    cmds:
      - go test -bench=. -benchmem ./cmd/s3copy

  cover:
    cmds:
      - go test -cover -coverprofile=coverage.out ./cmd/s3copy
      - go tool cover -html=coverage.out -o coverage.html
    generates:
      - coverage.out
      - coverage.html

  build:
    cmds:
      - goreleaser build --single-target --snapshot
  
  build-dev:
    cmds:
      - go build -o s3copy{{.SUFFIX}} ./cmd/s3copy

  release:
    cmds:
      - git tag -a v1.2.0 -m "Release v1.2.0"
      - git push origin v1.2.0
      - goreleaser release